- name: Install Docker and Deploy Image
  hosts: centos
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install plugins
      command: dnf -y install dnf-plugins-core

    - name: Add docker repository
      command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
  

    - name: Pull Docker image from Docker Hub
      community.docker.docker_image:
        name: "marwanalanani/python-app-image:latest"
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: weather-app
        image: "marwanalanani/python-app-image:latest"
        state: started
        restart_policy: always
